-- Run this once in Supabase SQL Editor before using learning programme registration.

alter table public.students add column if not exists email text;
create unique index if not exists idx_students_email_lower
    on public.students (lower(email)) where email is not null;
create unique index if not exists idx_accounts_email_lower
    on public.accounts (lower(email)) where email is not null and email <> '';

create table if not exists public.learning_programs (
    id bigint generated by default as identity primary key,
    publisher_account_id bigint references public.accounts(id) on delete set null,
    publisher_name text not null,
    title text not null,
    format text not null check (format in ('Certification', 'Workshop', 'Mentorship')),
    mode text not null default 'Online',
    duration text not null,
    skills text[] not null default '{}',
    audience text not null default 'Students',
    description text not null,
    created_at timestamptz not null default now(),
    unique (publisher_name, title)
);

create table if not exists public.programme_registrations (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    learning_program_id bigint not null references public.learning_programs(id) on delete cascade,
    status text not null default 'Registered' check (status in ('Registered', 'Cancelled', 'Completed')),
    registered_at timestamptz not null default now(),
    unique (student_id, learning_program_id)
);

create index if not exists idx_programme_registrations_student
    on public.programme_registrations(student_id);

insert into public.learning_programs
    (publisher_name, title, format, mode, duration, skills, audience, description)
values
    ('AryaVeda Pharmaceuticals', 'GMP & Ayurvedic Pharma Quality Essentials', 'Certification', 'Hybrid · New Delhi', '4 weeks', array['quality-assurance','pharmacognosy','medical-documentation'], 'Students & recent graduates', 'Learn GMP fundamentals for Ayurvedic formulations, including batch records and quality documentation. After registering, our learning team will email the joining schedule and pre-work.'),
    ('Swasthya Research Hospital', 'Evidence-Based Panchakarma Practice', 'Workshop', 'On-site · Delhi', '2 days', array['panchakarma','clinical-practice','research-ethics'], 'Students & faculty', 'Join clinical mentors for a practical Panchakarma workshop focused on patient safety, documentation, and evidence-led care. Bring your college ID on the first day.'),
    ('Prana Integrative Care', 'Yoga Therapy Case Documentation', 'Mentorship', 'Online', '6 weeks', array['yoga-therapy','medical-documentation','patient-counselling'], 'Students', 'Build a supervised case-documentation portfolio for yoga therapy. The publisher will send your mentor group and first-session link after registration.')
on conflict (publisher_name, title) do update set
    format = excluded.format,
    mode = excluded.mode,
    duration = excluded.duration,
    skills = excluded.skills,
    audience = excluded.audience,
    description = excluded.description;
