-- Run once in Supabase SQL Editor after the learning-programmes migration.

create table if not exists public.announcements (
    id bigint generated by default as identity primary key,
    publisher_account_id bigint not null references public.accounts(id) on delete cascade,
    opportunity_id bigint references public.opportunities(id) on delete cascade,
    learning_program_id bigint references public.learning_programs(id) on delete cascade,
    subject text not null,
    message text not null,
    created_at timestamptz not null default now(),
    check (
        (opportunity_id is not null and learning_program_id is null)
        or (opportunity_id is null and learning_program_id is not null)
    )
);

create table if not exists public.announcement_recipients (
    announcement_id bigint not null references public.announcements(id) on delete cascade,
    student_id bigint not null references public.students(id) on delete cascade,
    is_read boolean not null default false,
    primary key (announcement_id, student_id)
);

create index if not exists idx_announcement_recipients_student
    on public.announcement_recipients(student_id);
create index if not exists idx_announcements_publisher
    on public.announcements(publisher_account_id, created_at desc);
