-- SkillBridge schema for Supabase PostgreSQL.
-- Run this once in Supabase Dashboard > SQL Editor.

create table if not exists public.students (
    id bigint generated by default as identity primary key,
    name text not null,
    username text not null unique,
    password_hash text not null,
    headline text default 'Emerging professional building industry-ready skills.',
    bio text default '',
    created_at timestamptz default now()
);

create table if not exists public.accounts (
    id bigint generated by default as identity primary key,
    role text not null check(role in ('industry', 'academician')),
    name text not null,
    username text not null unique,
    password_hash text not null,
    organisation text default '',
    email text default '',
    verified boolean default false,
    created_at timestamptz default now()
);

create table if not exists public.skills (
    id bigint generated by default as identity primary key,
    name text not null unique,
    category text default 'General'
);

create table if not exists public.student_skills (
    student_id bigint not null references public.students(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    primary key(student_id, skill_id)
);

create table if not exists public.student_skill_levels (
    student_id bigint not null references public.students(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    level text not null check(level in ('Beginner', 'Intermediate', 'Expert')),
    score integer default 0,
    primary key(student_id, skill_id)
);

create table if not exists public.opportunities (
    id bigint generated by default as identity primary key,
    title text not null,
    company text default 'N/A',
    type text default 'Internship',
    description text default '',
    location text default 'Remote / Hybrid',
    duration text default 'Flexible',
    posted_by_account_id bigint references public.accounts(id) on delete set null,
    created_at timestamptz default now()
);

create table if not exists public.opportunity_skills (
    opportunity_id bigint not null references public.opportunities(id) on delete cascade,
    skill_id bigint not null references public.skills(id) on delete cascade,
    weight_type text not null check(weight_type in ('required', 'preferred')),
    primary key(opportunity_id, skill_id, weight_type)
);

create table if not exists public.applications (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    opportunity_id bigint not null references public.opportunities(id) on delete cascade,
    status text not null default 'Submitted' check(status in ('Submitted', 'Under Review', 'Shortlisted', 'Interview', 'Selected', 'Not Selected')),
    applied_at timestamptz default now(),
    updated_at timestamptz default now(),
    unique(student_id, opportunity_id)
);

create table if not exists public.portfolio_items (
    id bigint generated by default as identity primary key,
    student_id bigint not null references public.students(id) on delete cascade,
    item_type text not null check(item_type in ('Project', 'Certification', 'Achievement', 'Internship')),
    title text not null,
    issuer text default '',
    link text default '',
    description text default '',
    verified boolean default false,
    created_at timestamptz default now()
);

create table if not exists public.notifications (
    id bigint generated by default as identity primary key,
    account_id bigint not null references public.accounts(id) on delete cascade,
    message text not null,
    link text default '',
    is_read boolean default false,
    created_at timestamptz default now()
);

create index if not exists idx_student_skills_student on public.student_skills(student_id);
create index if not exists idx_opportunity_skills_opp on public.opportunity_skills(opportunity_id);
create index if not exists idx_opportunities_poster on public.opportunities(posted_by_account_id);

-- Email verification (OTP), added for account verification flow.
alter table public.accounts add column if not exists verification_code text;
alter table public.accounts add column if not exists verification_expires timestamptz;

-- Collaboration requests: academicians reaching out to industry partners.
create table if not exists public.collaboration_requests (
    id bigint generated by default as identity primary key,
    academician_id bigint not null references public.accounts(id) on delete cascade,
    industry_account_id bigint not null references public.accounts(id) on delete cascade,
    opportunity_id bigint references public.opportunities(id) on delete set null,
    message text not null,
    status text not null default 'Sent' check(status in ('Sent', 'Acknowledged', 'Declined')),
    created_at timestamptz default now()
);

create index if not exists idx_collab_requests_academician on public.collaboration_requests(academician_id);
create index if not exists idx_collab_requests_industry on public.collaboration_requests(industry_account_id);
